### ISSUE TITLE
openEHR-EHR-ACTION.medication_dips.v1

### ISSUE THREAD

**Issue by bjornna** [bjornna/dips-ckm#40]
Denne arketypen ser ut til å være kopi av openEHR-EHR-ACTION.medication.v0. 
Den har ingen beskrivelse av hva som er spesifikt og når den skal brukes fremfor de andre medikasjonsarketypene.

**Comment by HildeHollas** [comment]
Er ikke dette den versjonen av ACTION.medication som nå skal brukes i 17.1 (øye, plo?) ? Den er iallefall navngitt etter standard for navngiving av ikke godkjente arketyper/v0-arketyper, som skal i produksjon.Mvh Hilde-------- Original Message --------Subject: [bjornna/dips-ckm] openEHR-EHR-ACTION.medication_dips.v1 (#40)From: Bjørn Næss To: bjornna/dips-ckm CC: Subscribed Denne arketypen ser ut til å være kopi av openEHR-EHR-ACTION.medication.v0.
Den har ingen beskrivelse av hva som er spesifikt og når den skal brukes fremfor de andre medikasjonsarketypene.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bjornna/dips-ckm","title":"bjornna/dips-ckm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bjornna/dips-ckm"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"openEHR-EHR-ACTION.medication_dips.v1 (#40)"}],"action":{"name":"View Issue","url":"https://github.com/bjornna/dips-ckm/issues/40"}}}

**Comment by bjornna** [comment]
Ja. Jeg antar også dette. Da må vi oppdatere use/misuse feltene slik at vi kan lese i arketypen hva den skal brukes til.

**Comment by bjornna** [comment]
Hvem tar ansvar for å oppdatere use/misuse feltene for denne arketypen?

**Comment by HildeHollas** [comment]
Jeg ordner det over helga.Mvh Hilde 😊Sendt fra min mobiltlf, så mld kan være noe kort-------- Original Message --------Subject: Re: [bjornna/dips-ckm] openEHR-EHR-ACTION.medication_dips.v1 (#40)From: Bjørn Næss To: bjornna/dips-ckm CC: HildeHollas ,Comment Hvem tar ansvar for å oppdatere use/misuse feltene for denne arketypen?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bjornna/dips-ckm","title":"bjornna/dips-ckm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bjornna/dips-ckm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bjornna in #40: Hvem tar ansvar for å oppdatere use/misuse feltene for denne arketypen?"}],"action":{"name":"View Issue","url":"https://github.com/bjornna/dips-ckm/issues/40#issuecomment-309235719"}}}

**Comment by bjornna** [comment]
Kan vi lukke denne "issue" nå?

**Comment by HildeHollas** [comment]
Ja, så vidt jeg husker var det ikke noe annet enn å følge opp høringsrundene. Den er nå ute på den 3. høringsrunden, og vil snart bli godkjent...tror jeg.Hilde :-)Sendt fra min mobiltlf, så mld kan være noe kort-------- Original Message --------Subject: Re: [bjornna/dips-ckm] openEHR-EHR-ACTION.medication_dips.v1 (#40)From: Bjørn Næss To: bjornna/dips-ckm CC: HildeHollas ,Comment Kan vi lukke denne "issue" nå?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bjornna/dips-ckm","title":"bjornna/dips-ckm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bjornna/dips-ckm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bjornna in #40: Kan vi lukke denne \"issue\" nå?"}],"action":{"name":"View Issue","url":"https://github.com/bjornna/dips-ckm/issues/40#issuecomment-340241649"}}}
